### PR TITLE
Multiple features added

### LINKED ISSUE #11: Multiple Feature requests
After merging #9 and closing #10, these features need to be implemented before adding repository to pythonindia org.

- The bot retweets its own tweets if someone retweets them. Case in reference.

 

Possible Solution suggested by @inovizz  - Maintain an array original tweet ids, to avoid duplication clean it up after every couple of days in case of retweets.

- Bot needs to like tweets as well. 
- The retweet part of the code doesn't look good to me, can me do retweet with comment as referenced here - https://stackoverflow.com/a/33620770/1356851 (In comment we need to mention #PyConIndia2018 and #PyConIndia no need to add RT and twitter handle again for now)

### PR DESCRIPTION
**Pull request by vipulgupta2048**
- Removed Retweeting by appending "RT" (Old Practise)
- Added Retweet with comments with hashtags (New Practise by embedding tweets)
- Added Following followers of Gillsbot (New)
- Added Hastag --> #pyconindia (in searchterms)
- Added more comments (For better documentation)
- PyLint score 9.62 (Show-off)
- Fixes #11 
- Added like tweet feature (Much needed)

Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
The conflict in this PR is impossible to resolve just for a simple reason because the files that are conflicting doesn't exist in that location and have been moved to the directory `scripts`
Hence my suggestion would be to approve and merge #10 and review this. When done we can move forward on fixing the conflicts when the master branch is updated.

**Comment by inovizz** [comment]
LGTM :+1:

**Comment by vipulgupta2048** [comment]
@encodedgeek

**Comment by vipulgupta2048** [comment]
@inovizz Thanks, merge conflicts have been removed. Ready to go. Waiting for another review.

**Comment by Rohithgilla12** [comment]
Hey, I think this is now perfect and good to go and yeah @a2un , this can also be used as generic one, by just changing the config file is what I think.
Let's see what @inovizz  and @vipulgupta2048 say

**Pull request merged**
