### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Rohithgilla12**

### CODE REVIEW

**Review by vipulgupta2048 — CHANGES_REQUESTED** [review]
- I removed the hit count for a reason. I found it to be quite useless and the hits are not calculated accurately. Every time README.md is changed in local, it registered a hit.

**Comment by vipulgupta2048** [comment]
@Rohithgilla12  I have added some changes, please review the same.

**Review by Rohithgilla12 — COMMENTED** [review]
Yeah cool, this is nice , go forward

**Review by vipulgupta2048 — APPROVED** [review]
Made the changes as per review. Good to go.

**Pull request merged**
